### DISCUSSION TITLE
[HELP] Rechte und Rollen funktionieren nicht

### DISCUSSION THREAD

**Discussion by ghost** [urlaubsverwaltung/zeiterfassung#321] [Q&A] [answered]
Ich habe das Zeiterfassungstool mithilfe von Docker Compose erfolgreich eingerichtet. Das Problem ist jedoch, dass weder die Standardnutzer noch neu erstellte Nutzer nach der Zuweisung von Rollen und Rechten in der eigentlichen Anwendung die erwarteten Funktionen nutzen können. Zum Beispiel können weder Office noch Boss die Arbeitszeiten der Nutzer einstellen. Der einzige Unterschied zwischen Boss & Office und den Nutzern besteht darin, dass Boss & Office die Berichte anderer Nutzer herunterladen können (auch hier ist die Benutzeroberfläche jedoch nicht so schön wie in der offiziellen Demo).

Anbei noch meine docker-compose.yml

```
version: '3.8'
services:
  zeiterfassung:
    image: ghcr.io/urlaubsverwaltung/zeiterfassung/zeiterfassung:1.0.1
    container_name: zeiterfassung-app
    ports:
      - '${ZEITERFASSUNG_PORT}:${ZEITERFASSUNG_PORT}'
    environment:
      SERVER_PORT: ${ZEITERFASSUNG_PORT}
      # Database
      SPRING_DATASOURCE_URL: jdbc:postgresql://${IP}:${POSTGRES_PORT}/zeiterfassung
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: org.postgresql.Driver
      # Mail
      ZEITERFASSUNG_MAIL_FROM: zeiterfassung@example.org
      ZEITERFASSUNG_MAIL_FROMDISPLAYNAME: zeiterfassung
      ZEITERFASSUNG_MAIL_REPLYTO: replyto@example.org
      ZEITERFASSUNG_MAIL_REPLYTODISPLAYNAME: replyto
      SPRING_MAIL_HOST: ${HOSTNAME}
      SPRING_MAIL_PORT: ${MAILHOG_PORT_1}
      # OpenID Connect identity provider
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_DEFAULT_CLIENT-ID: zeiterfassung
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_DEFAULT_CLIENT-SECRET: zeiterfassung-secret
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_DEFAULT_CLIENT-NAME: zeiterfassung
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_DEFAULT_PROVIDER: default
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_DEFAULT_SCOPE: openid,profile,email,roles
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_DEFAULT_AUTHORIZATION-GRANT-TYPE: authorization_code
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_DEFAULT_REDIRECT-URI: http://{baseHost}:${ZEITERFASSUNG_PORT}/login/oauth2/code/{registrationId}
      SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_DEFAULT_ISSUER-URI: http://${IP}:${KEYCLOAK_PORT}/realms/zeiterfassung-realm
      ZEITERFASSUNG_SECURITY_OIDC_SERVER-URL: http://${IP}:${KEYCLOAK_PORT}/auth
      ZEITERFASSUNG_SECURITY_OIDC_LOGIN-FORM-URL: http://${IP}:${ZEITERFASSUNG_PORT}/oauth2/authorization/default
      SPRING_AUTOCONFIGURE_EXCLUDE: org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration
    depends_on:
      keycloak:
        condition: service_healthy
      postgres:
        condition: service_healthy
      mailhog:
        condition: service_started

  postgres:
    image: postgres:9.6
    container_name: zeiterfassung-db
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    environment:
      POSTGRES_DB: zeiterfassung
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      PGPORT: ${POSTGRES_PORT}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -h ${IP} -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: zeiterfassung-mail
    ports:
      - '${MAILHOG_PORT_0}:8025'
      - '${MAILHOG_PORT_1}:1025'

  keycloak:
    build: .
    image: quay.io/keycloak/keycloak:20.0.1
    container_name: zeiterfassung-auth
    environment:
      KC_HOSTNAME_STRICT: 'false'
      KC_HOSTNAME_STRICT_HTTPS: 'false'
      KC_HEALTH_ENABLED: 'true'
      KC_METRICS_ENABLED: 'true'
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://${IP}:${POSTGRES_PORT}/zeiterfassung
      KC_DB_USERNAME: user
      KC_DB_PASSWORD: password
      KC_HOSTNAME: ${HOSTNAME}
      KC_HTTP_PORT: ${KEYCLOAK_PORT}
      KC_HTTP_ENABLED: 'true'
      KC_FEATURES: token-exchange
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ${PWD}/volumes/keycloak:/opt/keycloak/data/import
    ports:
      - '${KEYCLOAK_PORT}:${KEYCLOAK_PORT}'
    healthcheck:
      test: curl --head -fsS http://${IP}:${KEYCLOAK_PORT}/health/ready
      interval: 10s
      timeout: 5s
      retries: 10
```
