### DISCUSSION TITLE
Authentifizierung mit anderen OpenID Providern (z.B. Authentik)

### DISCUSSION THREAD

**Discussion by bekanne** [urlaubsverwaltung/zeiterfassung#436] [Q&A] [answered]
Wie ist es denn möglich einen anderen OpenID Provider anzubinden (außer Keycloak)?

Hat vielleicht jemand Erfahrung, wie man die Konfiguration richtig setzt?

Mir ist es mit Authentik nicht gelungen. Ich werde nur auf eine Seite von Authentik weitergeleitet, aber mir scheint es nicht, dass die beiden Dienste miteinander kommunizieren können.

Das hier ist meine Konfiguration in der docker-compose.yml:

```
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_DEFAULT_CLIENT-ID: ************
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_DEFAULT_CLIENT-SECRET: "*************"
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_DEFAULT_CLIENT-NAME: zeiterfassung
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_DEFAULT_PROVIDER: default
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_DEFAULT_SCOPE: openid,profile,email,roles
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_DEFAULT_AUTHORIZATION-GRANT-TYPE: authorization_code
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_DEFAULT_REDIRECT-URI: https://zeiterfassung.my-domain.de/login/oauth2/code/zeiterfassung
      SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_DEFAULT_ISSUER-URI: https://authentik.my-domain.de/application/o/zeiterfassung/
      ZEITERFASSUNG_SECURITY_OIDC_SERVER-URL: https://authentik.my-domain.deapplication/o/authorize/
      ZEITERFASSUNG_SECURITY_OIDC_LOGIN-FORM-URL: https://authentik.my-domain.de/if/flow/default-authentication-flow/
      SPRING_AUTOCONFIGURE_EXCLUDE: org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration
```

**Comment by bekanne** [comment, marked as answer]
Ich habe es hinbekommen mit folgenden URL-Einstellungen:

```yaml
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_DEFAULT_REDIRECT-URI: https://zeiterfassung.my-domain.de/login/oauth2/code/{registrationId}
      SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_DEFAULT_ISSUER-URI: https://authentik.my-domain.de/application/o/zeiterfassung/
      ZEITERFASSUNG_SECURITY_OIDC_LOGIN-FORM-URL: https://zeiterfassung.my-domain.de/oauth2/authorization/default
```

Das Problem war, dass es keine Dokumentation zu der Einstellung "ZEITERFASSUNG_SECURITY_OIDC_LOGIN-FORM-URL" gibt. Ich hatte keine Ahnung, was ich da eintragen soll und warum.
