### ISSUE TITLE
Support für andere OIDC Provider als Keycloak

### ISSUE THREAD

**Issue by grafjo** [urlaubsverwaltung/zeiterfassung#1269]
aktuell wird nur Keycloak als OIDC Provider unterstützt.

Ziel sollte es sein, verschiedene OIDC Provider zu integrieren. Die Konfiguration erfolgt via [Spring Boot Properties](https://docs.spring.io/spring-security/reference/servlet/oauth2/login/core.html#oauth2login-boot-property-mappings).

Die Zeiterfassung benötigt dafür Zugriff auf folgende Claims:
* openid (sub)
* profile (given_name, family_name)
* email

Hintergrund:
* https://github.com/urlaubsverwaltung/zeiterfassung/discussions/348
* https://github.com/urlaubsverwaltung/zeiterfassung/discussions/436

**Comment by grafjo** [comment]
Beispiel zum Anlegen einer App in Entra-Id:
* https://urlaubsverwaltung.cloud/hilfe/kundenportal/sso/azuread/#schritt-1-neue-app-registrierung-im-azure-ad-durchfuehren
* https://urlaubsverwaltung.cloud/hilfe/kundenportal/sso/azuread/#schritt-3-fuer-app-registrierung-umleitungs-uri-konfigurieren

`REPLACE-WITH-`-Werte müssen aus der Entra Id App übernommen werden

```yaml
spring:
  security:
    oauth2:
      client:
        registration:
          default:
            authorization-grant-type: authorization_code
            client-id: REPLACE-WITH-CLIENT-ID
            client-name: zeiterfassung
            client-secret: REPLACE-WITH-CLIENT-SECRET
            provider: default
            redirect-uri: https://{baseHost}/login/oauth2/code/{registrationId}
            scope: openid,profile,email
        provider:
          default:
            issuer-uri: https://login.microsoftonline.com/REPLACE-WITH-ENTRA-TENANT-UUID/v2.0
```
